# Generated by Django 5.1.3 on 2025-04-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата выставки')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('venue', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Выставка',
                'verbose_name_plural': 'Выставки',
                'ordering': ['-date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_url', models.URLField(verbose_name='URL для <iframe> или видеофайл')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Видео для About',
                'verbose_name_plural': 'Видео для About',
                'ordering': ['order'],
            },
        ),
    ]
