# Generated by Django 5.1.3 on 2024-11-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Painting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("created_at", models.DateField()),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("material", models.CharField(max_length=100)),
                ("dimensions", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="paintings/")),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
