# Generated by Django 5.1.3 on 2024-11-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="painting",
            options={"verbose_name": "Картина", "verbose_name_plural": "Картины"},
        ),
        migrations.AlterField(
            model_name="painting",
            name="category",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Категория"
            ),
        ),
        migrations.AlterField(
            model_name="painting",
            name="created_at",
            field=models.DateField(verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="painting",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="painting",
            name="dimensions",
            field=models.CharField(max_length=50, verbose_name="Размеры"),
        ),
        migrations.AlterField(
            model_name="painting",
            name="image",
            field=models.ImageField(upload_to="paintings/", verbose_name="Изображение"),
        ),
        migrations.AlterField(
            model_name="painting",
            name="material",
            field=models.CharField(max_length=100, verbose_name="Материал"),
        ),
        migrations.AlterField(
            model_name="painting",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="painting",
            name="upload_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата загрузки"),
        ),
    ]
