# Generated by Django 5.1.3 on 2025-04-23 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_alter_painting_image_paintingimage'),
        ('artworks', '0004_merge_20250420_2230'),
    ]

    operations = [
    ]
