version: '3'

services:
  db:
    image: postgres:16.3-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - art_gallery_network

  web:
    build: .
#    command: gunicorn art_gallery.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - art_gallery_network

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - web
    networks:
      - art_gallery_network

volumes:
  postgres_data:
  static-volume:
  media-volume:

networks:
  art_gallery_network:
    driver: bridge
