version: '3'

services:
  db:
    image: postgres:16.3-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - art_gallery_network

  web:
    build: .
    volumes:
      - .:/app
      - static-volume:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - art_gallery_network

  nginx:
    image: nginx:1.25
    restart: always
    ports:
      - "8081:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static-volume:/app/staticfiles
      - ./media:/app/media
      - ./ssl:/app/ssl
    depends_on:
      - web
    networks:
      - art_gallery_network

volumes:
  postgres_data:
  static-volume:
  media-volume:

networks:
  art_gallery_network:
    driver: bridge
